[package]
name = "smart-read"
version = "0.2.1"
edition = "2021"
license = "MIT"
description = "complex but easy ways to read user input"
repository = "https://github.com/What42Pizza/rust-smart-read"
readme = "readme.md"
keywords = ["stdin", "io", "read", "input"]
categories = ["command-line-interface"]
