[package]
name = "smart-read"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "complex but easy ways to read user input"
keywords = ["stdin", "io", "read", "input"]
categories = ["command-line-interface"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
